#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your 
# load-balancer IP (lb-01). Let’s also add other subdomains to make our life
# easier, and write a Bash script that will display information about 
# subdomains.

display_info ()
{
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
    then
	display_info "$1" "$subdomain"
    fi
done
