#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) 
# using curl, it must return a page that contains the string Holberton School
# As an answer file, write a Bash script that configures a new Ubuntu machine
# to respect above requirements (this script will be run on the server itself)
# You can’t use systemctl for restarting nginx

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Holberton School" > /usr/share/nginx/html/index.html
