#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) 
# using curl, it must return a page that contains the string Holberton School
# As an answer file, write a Bash script that configures a new Ubuntu machine
# to respect above requirements (this script will be run on the server itself)
# You can’t use systemctl for restarting nginx
# Configure Nginx so that its HTTP response contains a custom header (on web-01
# and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx
# is running on
# Write 0-custom_http_response_header so that it configures a brand new Ubuntu
# machine to the requirements asked in this task

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
