#!/usr/bin/env bash
# a Bash script that displays a list of currently running processes. Must show
# all processes, for all users, including those which might not have a TTY
# display in a user-oriented format show process hierarchy

ps axuf
