#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd. Your script
# should only display: username, user id, home directory path for the user

while IFS= read -r LINE; do
    echo "$LINE" | cut -d':' -f1,4,7
done < /etc/passwd
