#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and: displays bad luck for the
# 4th loop iteration, displays good luck for the 8th loop iteration and
# displays Holberton School for the other iterations

COUNTER=1
while [ "$COUNTER" -le 10 ]; do
    if [ $COUNTER -eq 4 ]; then
	echo "bad luck"
    elif [ $COUNTER -eq 8 ]; then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    let COUNTER=COUNTER+1
done
