#!/usr/bin/env bash
# Change localhost to 127.0.0.2
# Change facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts
