#!/usr/bin/env bash
# A Bash script that configures the container to fit the below requirements
# Nginx must be running as nginx user
# Nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo chmod 777 /etc/nginx/sites-available/default
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
