#!/usr/bin/env bash
# A Bash script that configures the container to fit the below requirements
sudo chmod 777 /etc/nginx/nginx.conf 
sudo sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sudo chmod 777 /etc/nginx/sites-available/default
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
