#!/usr/bin/env bash
# A Bash script that configures the container to fit the below requirements
chmod 777 /etc/nginx/nginx.conf
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
chmod 777 /etc/nginx/sites-available/default
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
